// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumok-2DWQ82lR63dgyOWwtWwwI2lpPa4',
    appId: '1:162597917483:web:38d037f36035579fce2b6e',
    messagingSenderId: '162597917483',
    projectId: 'theatre-c77b0',
    authDomain: 'theatre-c77b0.firebaseapp.com',
    databaseURL: 'https://theatre-c77b0-default-rtdb.firebaseio.com',
    storageBucket: 'theatre-c77b0.appspot.com',
    measurementId: 'G-KBQT09RBF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDneMgq6QUArC95pouKW9dPkf-M0lRz0',
    appId: '1:162597917483:android:ea708b226430a37ece2b6e',
    messagingSenderId: '162597917483',
    projectId: 'theatre-c77b0',
    databaseURL: 'https://theatre-c77b0-default-rtdb.firebaseio.com',
    storageBucket: 'theatre-c77b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNdUGxMZpMwMXjgU5s-5dcFojm9eMpwCQ',
    appId: '1:162597917483:ios:ac7fc515b95f7b2dce2b6e',
    messagingSenderId: '162597917483',
    projectId: 'theatre-c77b0',
    databaseURL: 'https://theatre-c77b0-default-rtdb.firebaseio.com',
    storageBucket: 'theatre-c77b0.appspot.com',
    iosClientId: '162597917483-9b68i6bnvf3o4nvb19psl38oquocsdui.apps.googleusercontent.com',
    iosBundleId: 'com.pranjal.theatre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNdUGxMZpMwMXjgU5s-5dcFojm9eMpwCQ',
    appId: '1:162597917483:ios:ac7fc515b95f7b2dce2b6e',
    messagingSenderId: '162597917483',
    projectId: 'theatre-c77b0',
    databaseURL: 'https://theatre-c77b0-default-rtdb.firebaseio.com',
    storageBucket: 'theatre-c77b0.appspot.com',
    iosClientId: '162597917483-9b68i6bnvf3o4nvb19psl38oquocsdui.apps.googleusercontent.com',
    iosBundleId: 'com.pranjal.theatre',
  );
}
